### ISSUE TITLE
Use an Attribute object?

### ISSUE THREAD

**Issue by Spyder-Monkey** [mucsci-students/2022fa-420-LigmaPy#25]
https://github.com/mucsci-students/2022fa-420-LigmaPy/blob/0bf3ae1e95913b151182d96cbf2ac8533c0d7d94/saveload.py#L73

For the sake of future proofing the code, wouldn't it make more sense to append an Attribute object instead of a string containing the attribute's name?

**Comment by aaheinba** [comment]
Yeah i'll fix that, i just didn't have the attribute class when i originally wrote that.

**Comment by Spyder-Monkey** [comment]
All good, I'm just not able to load the attributes into the classes.

**Comment by astruxie** [comment]
Has this been fixed? If so we can close this!

**Comment by aaheinba** [comment]
issue should be fixed
