### ISSUE TITLE
Change interface's error messages

### ISSUE THREAD

**Issue by astruxie** [mucsci-students/2022fa-420-LigmaPy#38]
Change the "argument error"s into something more descriptive to the user

**Comment by jgeesaman** [comment]
Do you think we should also include the parameters the commands need in the help menu? Like we could say 
addClass _className_ Adds a new uniquely named class. That way the user can see exactly what information they need to provide for each command to run.

**Comment by Spyder-Monkey** [comment]
good idea. i'll add that sometime tonight.
