### ISSUE TITLE
after typing 'exit' when prompted y/n if user hits 'enter' without typing 'y' or 'n' user is prompted to save

### ISSUE THREAD

**Issue by aaheinba** [mucsci-students/2022fa-420-LigmaPy#48]
![image](https://user-images.githubusercontent.com/98050840/190266508-81114062-dc26-4ad6-a642-07bcf01cf87c.png)

**Comment by astruxie** [comment]
I think this might have been intended because typically when you're asked stuff and one of the options is capital, pressing enter picks that one. I coooould be wrong tho

**Comment by aaheinba** [comment]
No i typed "" when prompted y/n and still got the "type file to save to:" message

**Comment by astruxie** [comment]
Ahh so its accepting random input. @Spyder-Monkey

**Comment by aaheinba** [comment]
no anthying else but empty string rejects

**Comment by aaheinba** [comment]
i read his code "" and "y" are supposed to have the same action. Ignore this. Ill close it.
