### ISSUE TITLE
Interface Class

### ISSUE THREAD

**Issue by astruxie** [mucsci-students/2022fa-420-LigmaPy#5]
- [x] Implement Interface Class
- [x] Implement Attribute Class commands
- [x] Implement Save/Load commands
- [x] Implement List all Classes method
- [x] Implement List Specified Class method
- [x]  Implement List all Existing Relationships method
- [x]  Implement Help method
- [x]  Implement Exit method

Primary: Trevor
Secondary: Christian

Estimated Effort: 2
Hours Taken:
Actual Effort:

**Comment by trevor** [comment]
Hello

**Comment by astruxie** [comment]
> Hello

yo waddup random trevor that got tagged for some reason

**Comment by astruxie** [comment]
Also- it seems this can be closed. @Sh3p @Spyder-Monkey yaur or naur?

**Comment by Spyder-Monkey** [comment]
she do be complete

**Comment by astruxie** [comment]
@Spyder-Monkey @Sh3p Pls update ur hours taken and actual effort (I think this is graded & looked at by Hobbs)
